<!--<div id="menu">
    <div class="nav-wrapper container">
        <div class="logo-div">
            <H2>
                <a href="<?php /*echo URLROOT ;*/?>">
                    <?php /*echo SITENAME;*/?>
                </a>

            </H2>
        </div>
        <nav>
            <ul>
                <li>
                    <a href="<?php /*echo URLROOT ;*/?>">Accueil</a>
                </li>
                <li>
                    <a href="#">SCPI</a>
                </li>
                <li class="btn-login">
                    <a href="<?php /*echo URLROOT ;*/?>/users/login">Login</a>
                </li>
            </ul>
        </nav>
    </div>
</div>-->


<nav id="menu" class="navbar navbar-expand-md navbar-dark">
    <div class="nav-wrapper container">
        <div class="navbar-brand logo-div">
            <H2>
                <a href="<?php echo URLROOT ;?>">
                    <?php echo SITENAME;?>
                </a>

            </H2>
        </div>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarCollapse">

            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a  class="nav-link" href="<?php echo URLROOT ;?>">Accueil<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">SCPI</a>
                </li>
                <li class="btn-login">
                    <a class="nav-link" href="<?php echo URLROOT ;?>/users/login">Login</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
